# Generated by Django 2.2.4 on 2023-06-12 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='desc',
            field=models.TextField(default='nothing yet'),
            preserve_default=False,
        ),
    ]
